config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :boyfriends, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only:[] do
      member do
      post 'accept'
    end
    member do
      post 'reject'
    end
  end
  namespace :account do
    resources :bookings, only: [:index] do
      collection do
        get 'pending'
      end
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= 'navbar-trans fixed-top' if root_path  %>" style="background: linear-gradient(rgba(198,206,210,0.2) 1%, rgba(250,242,244,0.2) 100%) no-repeat 50% 50% / 100% 100%">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo1.gif"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item" style="padding-right: 8px">
          <%= link_to "Become a Boyfriend", new_boyfriend_path, class: "nav-link nav-btn" %>
        </li>
        <li class="nav-item" style="padding-right: 5px">
          <%= link_to "Browse", boyfriends_path , class: "nav-link nav-color" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My relationships", account_bookings_path(current_user), class: "dropdown-item" %>
            <%= link_to "Account", "#", class: "dropdown-item" %>
            <%= link_to "Pending Bookings", pending_account_bookings_path, class: "dropdown-item" %>
            <%= link_to "Refer Boyfriends", "#", class: "dropdown-item" %>
            <%= link_to "Gift a Boyfriend", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link nav-btn nav-login" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign-up", new_user_registration_path, class: "nav-link signup" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>